### ISSUE TITLE
I get error shown 'Composer is not installed.'

### ISSUE THREAD

**Issue by kawashimaken** [smizy/docker-eccube#1]
お世話になります。川島です。
色々検索して、ここに辿り着きました。
READMEの通り、一通りやってみましたが、最後ブラウザーで開いたときに、'Composer is not installed.'というメッセージが表示され、次に進まないところです。
phpフォルダ配下のDockerfileにcomposerをインストールscriptもありますし、composerをインストールしたメッセージもdocker-compose起動のとき確認できましたのに
少し不思議です。
この現象について何かご知恵をお貸しいただければと思います。
宜しくお願い致します。

**Comment by smizy** [comment]
@kawashimaken `docker-compose logs php`で出力されるログに何か手がかりになるようなものないでしょうか。

**Comment by kawashimaken** [comment]
早速お返事いただきありがとうございます。
`dockr-compose up`　して
ブラウザーで
localhost:8080/install 
localhost:8080 
localhost:8080/install.php
にアクセスして見て
同じメッセージ

```
Composer is not installed.
```

が表示され、それから `docker-compose logs php`で確認しますと、下記の通りになっております

``` bash
➜  docker git:(master) ✗ docker-compose logs php
Attaching to docker_php_1
php_1       | [19-Oct-2016 09:42:54] NOTICE: fpm is running, pid 1
php_1       | [19-Oct-2016 09:42:54] NOTICE: ready to handle connections
php_1       | 172.20.0.4 -  19/Oct/2016:09:43:47 +0000 "GET /html/index.php" 200
php_1       | 172.20.0.4 -  19/Oct/2016:09:43:52 +0000 "GET /html/index.php" 200
php_1       | 172.20.0.4 -  19/Oct/2016:09:49:25 +0000 "GET /html/index.php" 200
php_1       | 172.20.0.4 -  19/Oct/2016:09:50:18 +0000 "GET /install.php" 200
```

サーバーの設定等の問題ではなさそうですが、composer関連の情報はありませんでした。

**Comment by smizy** [comment]
@kawashimaken 手元の環境では再現できないのですが、`ec-cube/autoload.php`の

```
 :
 :
$autoload = __DIR__.'/vendor/autoload.php';

if (file_exists($autoload) && is_readable($autoload)) {
    $loader = require $autoload;
} else {
    die('Composer is not installed.');
}
```

この部分のファイル存在/読み込み判定で失敗しているようですね。
以下のコマンドの結果はどうなってるでしょうか。

```
$ docker-compose exec php ls -l vendor/autoload.php
-rw-r--r--    1 root     root           183 Sep 26 07:55 vendor/autoload.php
```

**Comment by kawashimaken** [comment]
@smizy お返事いただきありがとうございます。
おっしゃる通りに、ファイル存在/読み込み判定で失敗しているようですね。
`docker-compose up`　で起動した後
下記の結果となりました。

``` bash
➜  docker git:(master) ✗ docker-compose exec php ls -l vendor/autoload.php
ls: vendor/autoload.php: No such file or directory
```

やはりこのファイルがないですね。

php配下のDockerfileを見ていますと、composer 自体がインストールしていますが
ec-ecubeのフォルダーで一回 `composer install`を実行する必要がありますかね。（READMEに記述がないため、ec-cubeのフォルダーでcomposer install はしませんでした。）

**Comment by smizy** [comment]
@kawashimaken READMEの手順にあるunzipするeccubeのzipファイルはvendorディレクトリを含んでおり、必要なパッケージが同梱されているので、composer installは不要です。こちら同梱されてないでしょうか？

**Comment by kawashimaken** [comment]
@smizy ご指摘の通りでした！
原因は私が、github のzipファイルを使っていました。当然ですが、vendorディレクトリがありませんでした。（たまたまwgetがインストールしていなくて、油断しました。大変失礼しました。）

今、http://www.ec-cube.net/download/　
から直接zipファイルをダウンロードして配置し、
http://localhost:8080/install.php
にアクセスして初期設定の画面が表示されました！（こっちの方が同梱されていますね。なるほどです。）

ありがとうございました！ m(_._)m
次のステップを色々試してみます！引き続き宜しくお願い致します！

**Comment by ry0620** [comment]
23232
